### ISSUE TITLE
Statusbar styling

### ISSUE THREAD

**Issue by dmt0** [GBonnaire/jspreadsheet-plugins-and-editors#14]
### Plugin Name with version

"@jspreadsheet/statusbar": "2.2.0"

### JSpreadsheet version

v9.x

### Describe the bug

Minor issue: vertical alignment in statusbar is off. Here's css that works:

```css
.jss_statusbar .jss_statusbar_information {
  flex-grow: 100;
  font-size: 13px;
  padding-right: 5px;
  /* text-align: right; */
  /* vertical-align: middle; */
  display: flex;
  align-items: center;
  justify-content: right;
}
```

### Reproduction steps

```bash
1.
2.
3.
...
```
